version: '3'
services:
  backend:
   build:
      context: ./backend/.
      dockerfile: Dockerfile
   command: sh -c "npm ci && npm start"
   ports:
    - "8080:8080"
  frontend:
    build:
      context: ./frontend/.
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: sh -c "npm ci && npm start"
    depends_on:
      - backend


      